export const UI_OPEN_LEFT_DRAWER = 'UI_OPEN_LEFT_DRAWER';
export const UI_LEFT_DRAWER_CLOSE = 'UI_LEFT_DRAWER_CLOSE';
export const UI_CLOSE_LEFT_DRAWER = 'UI_CLOSE_LEFT_DRAWER';
export const UI_RIGHT_DRAWER_OPEN = 'UI_RIGHT_DRAWER_OPEN';
export const UI_RIGHT_DRAWER_CLOSE = 'UI_RIGHT_DRAWER_CLOSE';
export const UI_DIALOG_OPEN = 'UI_DIALOG_OPEN';
export const UI_DIALOG_CLOSE = 'UI_DIALOG_CLOSE';
export const UI_SNACKBAR_OPEN = 'UI_SNACKBAR_OPEN';
export const UI_SNACKBAR_CLOSE = 'UI_SNACBKBAR_CLOSE';
export const UI_TOGGLE_CARDS_DIALOG = 'UI_TOGGLE_CARDS_DIALOG';
export const UI_SELECT_CARD = 'UI_SELECT_CARD';
export const UI_SET_RIGHT_APPBAR_ICON = 'UI_SET_RIGHT_APPBAR_ICON';
export const UI_SET_APPBAR_TITLE = 'UI_SET_APPBAR_TITLE';
export const UI_TOGGLE_ASSIGN_MATERIAL_DIALOG =
    'UI_TOGGLE_ASSIGN_MATERIAL_DIALOG';
