export const AUTH_GET_SESSION_REQUEST = 'AUTH_GET_SESSION_REQUEST';
export const AUTH_GET_SESSION_SUCCESS = 'AUTH_GET_SESSION_SUCCESS';
export const AUTH_GET_SESSION_ERROR = 'AUTH_GET_SESSION_ERROR';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';
export const COLLECTION_CREATEMETA_REQUEST = 'COLLECTION_CREATEMETA_REQUEST';
export const COLLECTION_CREATEMETA_SUCCESS = 'COLLECTION_CREATEMETA_SUCCESS';
export const COLLECTION_CREATEMETA_ERROR = 'COLLECTION_CREATEMETA_ERROR';
export const COLLECTION_GET_REQUEST = 'COLLECTION_GET_REQUEST';
export const COLLECTION_GET_SUCCESS = 'COLLECTION_GET_SUCCESS';
export const COLLECTION_GET_ERROR = 'COLLECTION_GET_ERROR';
export const CARDS_GET_CARDS_REQUEST = 'CARDS_GET_CARDS_REQUEST';
export const CARDS_GET_CARDS_SUCCESS = 'CARDS_GET_CARDS_SUCCESS';
export const CARDS_GET_CARDS_ERROR = 'CARDS_GET_CARDS_ERROR';
export const CARDS_GET_CARD_REQUEST = 'CARDS_GET_CARD_REQUEST';
export const CARDS_GET_CARD_SUCCESS = 'CARDS_GET_CARD_SUCCESS';
export const CARDS_GET_CARD_ERROR = 'CARDS_GET_CARD_ERROR';
export const CARDS_CREATE_CARD_REQUEST = 'CARDS_CREATE_CARD_REQUEST';
export const CARDS_CREATE_CARD_SUCCESS = 'CARDS_CREATE_CARD_SUCCESS';
export const CARDS_CREATE_CARD_ERROR = 'CARDS_CREATE_CARD_ERROR';
export const CARDS_UPDATE_CARD_REQUEST = 'CARDS_UPDATE_CARD_REQUEST';
export const CARDS_UPDATE_CARD_SUCCESS = 'CARDS_UPDATE_CARD_SUCCESS';
export const CARDS_UPDATE_CARD_ERROR = 'CARDS_UPDATE_CARD_ERROR';
export const CARDS_DELETE_CARD_REQUEST = 'CARDS_DELETECARD_REQUEST';
export const CARDS_DELETE_CARD_SUCCESS = 'CARDS_DELETE_CARD_SUCCESS';
export const CARDS_DELETE_CARD_ERROR = 'CARDS_DELETE_CARD_ERROR';
export const CARDS_REM_TAG_REQUEST = 'CARDS_REM_TAG_REQUEST';
export const CARDS_REM_TAG_SUCCESS = 'CARDS_REM_TAG_SUCCESS';
export const CARDS_REM_TAG_ERROR = 'CARDS_REM_TAG_ERROR';
export const CARDS_ADD_TAG_REQUEST = 'CARDS_ADD_TAG_REQUEST';
export const CARDS_ADD_TAG_SUCCESS = 'CARDS_ADD_TAG_SUCCESS';
export const CARDS_ADD_TAG_ERROR = 'CARDS_ADD_TAG_ERROR';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_USERDATA_SUCCESS =
    'COLLECTION_UPDATE_USERDATA_SUCCESS';
export const COLLECTIONS_UPDATE_COLLECTION_REQUEST =
    'COLLECTIONS_UPDATE_COLLECTION_REQUEST';
export const COLLECTIONS_UPDATE_COLLECTION_SUCCESS =
    'COLLECTIONS_UPDATE_COLLECTION_SUCCESS';
export const COLLECTIONS_UPDATE_COLLECTION_ERROR =
    'COLLECTIONS_UPDATE_COLLECTION_ERROR';
export const COLLECTION_SUBMIT_REQUEST = 'COLLECTION_SUBMIT_REQUEST';
export const COLLECTION_SUBMIT_SUCCESS = 'COLLECTION_SUBMIT_SUCCESS';
export const COLLECTION_SUBMIT_ERROR = 'COLLECTION_SUBMIT_ERROR';
export const COLLECTION_RESET_REQUEST = 'COLLECTION_RESET_REQUEST';
export const COLLECTION_RESET_SUCCESS = 'COLLECTION_RESET_SUCCESS';
export const COLLECTION_RESET_ERROR = 'COLLECTION_RESET_ERROR';
export const COLLECTIONS_CREATE_COLLECTION_REQUEST =
    'COLLECTIONS_CREATE_COLLECTION_REQUEST';
export const COLLECTIONS_CREATE_COLLECTION_SUCCESS =
    'COLLECTIONS_CREATE_COLLECTION_SUCCESS';
export const COLLECTIONS_CREATE_COLLECTION_ERROR =
    'COLLECTIONS_CREATE_COLLECTION_ERROR';
export const COLLECTION_ADD_CARDS_REQUEST = 'COLLECTION_ADD_CARDS_REQUEST';
export const COLLECTION_ADD_CARDS_SUCCESS = 'COLLECTION_ADD_CARDS_SUCCESS';
export const COLLECTION_ADD_CARDS_ERROR = 'COLLECTION_ADD_CARDS_ERROR';
export const COLLECTION_DELETE_COLLECTION_REQUEST =
    'COLLECTION_DELETE_COLLECTION_REQUEST';
export const COLLECTION_DELETE_COLLECTION_SUCCESS =
    'COLLECTION_DELETE_COLLECTION_SUCCESS';
export const COLLECTION_DELETE_COLLECTION_ERROR =
    'COLLECTION_DELETE_COLLECTION_ERROR';
export const DATA_CREATE_REQUEST = 'DATA_CREATE_REQUEST';
export const DATA_CREATE_SUCCESS = 'DATA_CREATE_SUCCESS';
export const DATA_CREATE_ERROR = 'DATA_CREATE_ERROR';
export const DATA_GET_REQUEST = 'DATA_GET_REQUEST';
export const DATA_GET_SUCCESS = 'DATA_GET_SUCCESS';
export const DATA_GET_ERROR = 'DATA_GET_ERROR';
export const DB_CHANGE = 'DB_CHANGE';
export const DATA_UPDATE_REQUEST = 'DATA_UPDATE_REQUEST';
export const DATA_UPDATE_SUCCESS = 'DATA_UPDATE_SUCCESS';
export const DATA_UPDATE_ERROR = 'DATA_UPDATE_ERROR';
export const USER_INIT_REQUEST = 'USER_INIT_REQUEST';
export const USER_INIT_SUCCESS = 'USER_INIT_SUCCESS';
export const USER_INIT_ERROR = 'USER_INIT_ERROR';
export const MATERIAL_CREATE_REQUEST = 'MATERIAL_CREATE_REQUEST';
export const MATERIAL_CREATE_SUCCESS = 'MATERIAL_CREATE_SUCCESS';
export const MATERIAL_CREATE_ERROR = 'MATERIAL_CREATE_ERROR';
export const MATERIAL_CREATE_META_REQUEST = 'MATERIAL_META_CREATE_REQUEST';
export const MATERIAL_CREATE_META_SUCCESS = 'MATERIAL_META_CREATE_SUCCESS';
export const MATERIAL_CREATE_META_ERROR = 'MATERIAL_META_CREATE_ERROR';
export const MATERIAL_GET_SUCCESS = 'MATERIAL_GET_SUCCESS';
export const MATERIAL_META_GET_REQUEST = 'MATERIAL_META_GET_REQUEST';
export const MATERIAL_META_GET_SUCCESS = 'MATERIAL_META_GET_SUCCESS';
export const MATERIAL_META_GET_ERROR = 'MATERIAL_META_GET_ERROR';
export const MATERIAL_UPDATE_MATERIAL_REQUEST =
    'MATERIAL_UPDATE_MATERIAL_REQUEST';
export const MATERIAL_UPDATE_MATERIAL_SUCCESS =
    'MATERIAL_UPDATE_MATERIAL_SUCCESS';
export const MATERIAL_UPDATE_MATERIAL_ERROR = 'MATERIAL_UPDATE_MATERIAL_ERROR';
export const MATERIAL_UPDATE_META_REQUEST = 'MATERIAL_UPDATE_META_REQUEST';
export const MATERIAL_UPDATE_META_SUCCESS = 'MATERIAL_UPDATE_META_SUCCESS';
export const MATERIAL_UPDATE_META_ERROR = 'MATERIAL_UPDATE_META_ERROR';
export const MATERIAL_RESET_META_IN_WORKSHEET_REQUEST =
    'MATERIAL_RESET_META_IN_WORKSHEET_REQUEST';
export const MATERIAL_RESET_META_IN_WORKSHEET_SUCCESS =
    'MATERIAL_RESET_META_IN_WORKSHEET_SUCCESS';
export const MATERIAL_RESET_META_IN_WORKSHEET_ERROR =
    'MATERIAL_RESET_META_IN_WORKSHEET_ERROR';
export const MATERIAL_DELETE_REQUEST = 'MATERIAL_DELETE_REQUEST';
export const MATERIAL_DELETE_SUCCESS = 'MATERIAL_DELETE_SUCCESS';
export const MATERIAL_DELETE_ERROR = 'MATERIAL_DELETE_ERROR';
export const MATERIAL_DELETE_META_REQUEST = 'MATERIAL_DELETE_META_REQUEST';
export const MATERIAL_DELETE_META_SUCCESS = 'MATERIAL_DELETE_META_SUCCESS';
export const MATERIAL_DELETE_META_ERROR = 'MATERIAL_DELETE_META_ERROR';
export const UI_OPEN_LEFT_DRAWER = 'UI_OPEN_LEFT_DRAWER';
export const UI_LEFT_DRAWER_CLOSE = 'UI_LEFT_DRAWER_CLOSE';
export const UI_CLOSE_LEFT_DRAWER = 'UI_CLOSE_LEFT_DRAWER';
export const UI_RIGHT_DRAWER_OPEN = 'UI_RIGHT_DRAWER_OPEN';
export const UI_RIGHT_DRAWER_CLOSE = 'UI_RIGHT_DRAWER_CLOSE';
export const UI_DIALOG_OPEN = 'UI_DIALOG_OPEN';
export const UI_DIALOG_CLOSE = 'UI_DIALOG_CLOSE';
export const UI_SNACKBAR_OPEN = 'UI_SNACKBAR_OPEN';
export const UI_SNACKBAR_CLOSE = 'UI_SNACBKBAR_CLOSE';
export const UI_TOGGLE_CARDS_DIALOG = 'UI_TOGGLE_CARDS_DIALOG';
export const UI_SELECT_CARD = 'UI_SELECT_CARD';
export const UI_SET_RIGHT_APPBAR_ICON = 'UI_SET_RIGHT_APPBAR_ICON';
export const UI_TOGGLE_TAG_ID_FILTER = 'UI_TOGGLE_TAG_ID_FILTER';
export const UI_SET_APPBAR_TITLE = 'UI_SET_APPBAR_TITLE';
export const SESSION_GET_SESSION_ID_SUCCESS = 'SESSION_GET_SESSION_ID_SUCCESS';
