export const COLLECTION_SELECT = 'COLLECTION_SELECT';
export const COLLECTION_CREATEMETA_REQUEST = 'COLLECTION_CREATEMETA_REQUEST';
export const COLLECTION_CREATEMETA_SUCCESS = 'COLLECTION_CREATEMETA_SUCCESS';
export const COLLECTION_CREATEMETA_ERROR = 'COLLECTION_CREATEMETA_ERROR';
export const COLLECTION_GET_REQUEST = 'COLLECTION_GET_REQUEST';
export const COLLECTION_GET_SUCCESS = 'COLLECTION_GET_SUCCESS';
export const COLLECTION_GET_ERROR = 'COLLECTION_GET_ERROR';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_USERDATA_SUCCESS =
    'COLLECTION_UPDATE_USERDATA_SUCCESS';
export const COLLECTIONS_UPDATE_COLLECTION_REQUEST =
    'COLLECTIONS_UPDATE_COLLECTION_REQUEST';
export const COLLECTIONS_UPDATE_COLLECTION_SUCCESS =
    'COLLECTIONS_UPDATE_COLLECTION_SUCCESS';
export const COLLECTIONS_UPDATE_COLLECTION_ERROR =
    'COLLECTIONS_UPDATE_COLLECTION_ERROR';
export const COLLECTION_SUBMIT_REQUEST = 'COLLECTION_SUBMIT_REQUEST';
export const COLLECTION_SUBMIT_SUCCESS = 'COLLECTION_SUBMIT_SUCCESS';
export const COLLECTION_SUBMIT_ERROR = 'COLLECTION_SUBMIT_ERROR';
export const COLLECTION_RESET_REQUEST = 'COLLECTION_RESET_REQUEST';
export const COLLECTION_RESET_SUCCESS = 'COLLECTION_RESET_SUCCESS';
export const COLLECTION_RESET_ERROR = 'COLLECTION_RESET_ERROR';
export const COLLECTIONS_CREATE_COLLECTION_REQUEST =
    'COLLECTIONS_CREATE_COLLECTION_REQUEST';
export const COLLECTIONS_CREATE_COLLECTION_SUCCESS =
    'COLLECTIONS_CREATE_COLLECTION_SUCCESS';
export const COLLECTIONS_CREATE_COLLECTION_ERROR =
    'COLLECTIONS_CREATE_COLLECTION_ERROR';
export const COLLECTION_ADD_CARDS_REQUEST = 'COLLECTION_ADD_CARDS_REQUEST';
export const COLLECTION_ADD_CARDS_SUCCESS = 'COLLECTION_ADD_CARDS_SUCCESS';
export const COLLECTION_ADD_CARDS_ERROR = 'COLLECTION_ADD_CARDS_ERROR';
export const COLLECTION_REM_CARDS_REQUEST = 'COLLECTION_REM_CARDS_REQUEST';
export const COLLECTION_REM_CARDS_SUCCESS = 'COLLECTION_REM_CARDS_SUCCESS';
export const COLLECTION_REM_CARDS_ERROR = 'COLLECTION_REM_CARDS_ERROR';
export const COLLECTION_DELETE_COLLECTION_REQUEST =
    'COLLECTION_DELETE_COLLECTION_REQUEST';
export const COLLECTION_DELETE_COLLECTION_SUCCESS =
    'COLLECTION_DELETE_COLLECTION_SUCCESS';
export const COLLECTION_DELETE_COLLECTION_ERROR =
    'COLLECTION_DELETE_COLLECTION_ERROR';
export const COLLECTION_SELECTION_RESET = 'COLLECTION_SELECTION_RESET';
export const COLLECTION_UI_SHOW_ASSIGN_COLLECTION_DIALOG =
    'COLLECTION_UI_SHOW_ASSIGN_COLLECTION_DIALOG';
export const COLLECTION_UI_HIDE_ASSIGN_COLLECTION_DIALOG =
    'COLLECTION_UI_HIDE_ASSIGN_COLLECTION_DIALOG';

export const COLLECTIONS_ASSIGN_COLLECTION_REQUEST =
    'COLLECTIONS_ASSIGN_COLLECTION_REQUEST';
export const COLLECTIONS_ASSIGN_COLLECTION_SUCCESS =
    'COLLECTIONS_ASSIGN_COLLECTION_SUCCESS';
export const COLLECTIONS_ASSIGN_COLLECTION_ERROR =
    'COLLECTIONS_ASSIGN_COLLECTION_ERROR';
