// create
export const MATERIAL_CREATE_REQUEST = "MATERIAL_CREATE_REQUEST";
export const MATERIAL_CREATE_SUCCESS = "MATERIAL_CREATE_SUCCESS";
export const MATERIAL_CREATE_ERROR = "MATERIAL_CREATE_ERROR";

export const MATERIAL_CREATE_META_REQUEST = "MATERIAL_META/CREATE/REQUEST";
export const MATERIAL_CREATE_META_SUCCESS = "MATERIAL_META/CREATE/SUCCESS";
export const MATERIAL_CREATE_META_ERROR = "MATERIAL_META/CREATE/ERROR";

// read
// read -> material
export const MATERIAL_GET_SUCCESS = "MATERIAL_GET_SUCCESS";

// read -> meta
export const MATERIAL_META_GET_REQUEST = "MATERIAL_META/GET/REQUEST";
export const MATERIAL_META_GET_SUCCESS = "MATERIAL_META/GET/SUCCESS";
export const MATERIAL_META_GET_ERROR = "MATERIAL_META/GET/ERROR";

// update
// update -> material
export const MATERIAL_UPDATE_MATERIAL_REQUEST = "MATERIAL_UPDATE_MATERIAL_REQUEST";
export const MATERIAL_UPDATE_MATERIAL_SUCCESS = "MATERIAL_UPDATE_MATERIAL_SUCCESS";
export const MATERIAL_UPDATE_MATERIAL_ERROR = "MATERIAL_UPDATE_MATERIAL_ERROR";

// update -> meta
export const MATERIAL_UPDATE_META_REQUEST = "MATERIAL_UPDATE_META_REQUEST";
export const MATERIAL_UPDATE_META_SUCCESS = "MATERIAL_UPDATE_META_SUCCESS";
export const MATERIAL_UPDATE_META_ERROR = "MATERIAL_UPDATE_META_ERROR";

export const MATERIAL_RESET_META_IN_WORKSHEET_REQUEST = "MATERIAL_RESET_META_IN_WORKSHEET_REQUEST";
export const MATERIAL_RESET_META_IN_WORKSHEET_SUCCESS = "MATERIAL_RESET_META_IN_WORKSHEET_SUCCESS";
export const MATERIAL_RESET_META_IN_WORKSHEET_ERROR = "MATERIAL_RESET_META_IN_WORKSHEET_ERROR";

// delete

export const MATERIAL_DELETE_REQUEST = "MATERIAL_DELETE_REQUEST";
export const MATERIAL_DELETE_SUCCESS = "MATERIAL_DELETE_SUCCESS";
export const MATERIAL_DELETE_ERROR = "MATERIAL_DELETE_ERROR";

export const MATERIAL_DELETE_META_REQUEST = "MATERIAL_DELETE_META_REQUEST";
export const MATERIAL_DELETE_META_SUCCESS = "MATERIAL_DELETE_META_SUCCESS";
export const MATERIAL_DELETE_META_ERROR = "MATERIAL_DELETE_META_ERROR";
