export const GROUPS_GET_USER_GROUPS_REQUEST = 'GROUPS_GET_USER_GROUPS_REQUEST';
export const GROUPS_GET_USER_GROUPS_SUCCESS = 'GROUPS_GET_USER_GROUPS_SUCCESS';
export const GROUPS_GET_USER_GROUPS_ERROR = 'GROUPS_GET_USER_GROUPS_ERROR';
export const GROUPS_CREATE_REQUEST = 'GROUPS_CREATE_REQUEST';
export const GROUPS_CREATE_SUCCESS = 'GROUPS_CREATE_SUCCESS';
export const GROUPS_CREATE_ERROR = 'GROUPS_CREATE_ERROR';
export const GROUPS_ENABLE_COLLECTION_REQUEST =
    'GROUPS_ENABLE_COLLECTION_REQUEST';
export const GROUPS_ENABLE_COLLECTION_SUCCESS =
    'GROUPS_ENABLE_COLLECTION_SUCCESS';
export const GROUPS_ENABLE_COLLECTION_ERROR = 'GROUPS_ENABLE_COLLECTION_ERROR';
export const GROUPS_DISABLE_COLLECTION_REQUEST =
    'GROUPS_DISABLE_COLLECTION_REQUEST';
export const GROUPS_DISABLE_COLLECTION_SUCCESS =
    'GROUPS_DISABLE_COLLECTION_SUCCESS';
export const GROUPS_DISABLE_COLLECTION_ERROR =
    'GROUPS_DISABLE_COLLECTION_ERROR';
export const GROUPS_DELETE_REQUEST = 'GROUPS_DELETE_REQUEST';
export const GROUPS_DELETE_SUCCESS = 'GROUPS_DELETE_SUCCESS';
export const GROUPS_DELETE_ERROR = 'GROUPS_DELETE_ERROR';
export const GROUPS_GET_GROUP_REQUEST = 'GROUPS_GET_GROUP_REQUEST';
export const GROUPS_GET_GROUP_SUCCESS = 'GROUPS_GET_GROUP_SUCCESS';
export const GROUPS_GET_GROUP_ERROR = 'GROUPS_GET_GROUP_ERROR';
export const GROUPS_GET_GROUPS_REQUEST = 'GROUPS_GET_GROUPS_REQUEST';
export const GROUPS_GET_GROUPS_SUCCESS = 'GROUPS_GET_GROUPS_SUCCESS';
export const GROUPS_GET_GROUPS_ERROR = 'GROUPS_GET_GROUPS_ERROR';
export const GROUPS_ADD_COLLECTION_REQUEST = 'GROUPS_ADD_COLLECTION_REQUEST';
export const GROUPS_ADD_COLLECTION_SUCCESS = 'GROUPS_ADD_COLLECTION_SUCCESS';
export const GROUPS_ADD_COLLECTION_ERROR = 'GROUPS_ADD_COLLECTION_ERROR';
export const GROUPS_REM_COLLECTION_REQUEST = 'GROUPS_REM_COLLECTION_REQUEST';
export const GROUPS_REM_COLLECTION_SUCCESS = 'GROUPS_REM_COLLECTION_SUCCESS';
export const GROUPS_REM_COLLECTION_ERROR = 'GROUPS_REM_COLLECTION_ERROR';
export const GROUPS_ADD_GROUP_REQUEST = 'GROUPS_ADD_GROUP_REQUEST';
export const GROUPS_ADD_GROUP_SUCCESS = 'GROUPS_ADD_GROUP_SUCCESS';
export const GROUPS_ADD_GROUP_ERROR = 'GROUPS_ADD_GROUP_ERROR';
export const GROUPS_REM_GROUP_REQUEST = 'GROUPS_REM_GROUP_REQUEST';
export const GROUPS_REM_GROUP_SUCCESS = 'GROUPS_REM_GROUP_SUCCESS';
export const GROUPS_REM_GROUP_ERROR = 'GROUPS_REM_GROUP_ERROR';
