version: '3'
services:
    nginx:
        image: lumieducation/nginx:latest
        restart: always
        ports:
            - ${PORT}:80
        networks:
            - webnet
        volumes:
            - ./files:/usr/share/nginx/html/files
    lumi:
        image: lumieducation/lumi:latest
        restart: always
        networks:
            - webnet
        environment:
            - LUMI_ID=${ID}
            - NODE_ENV=${NODE_ENV}
            - KEY=${KEY}
            - DB=${DB}
            - SENTRY=${SENTRY}
            - SENTRY_PUBLIC=${SENTRY_PUBLIC}
            - DEBUG=*
        volumes:
            - ./files:/srv/build/files
            - ./h5p:/srv/build/h5p
            - ./.env:/srv/.env
            - ./lumi_sshkey:/srv/lumi_sshkey
        depends_on:
            - 'couchdb'
    apd:
        image: lumieducation/apd:latest
        privileged: true
        restart: always
        ports:
            - '53:53'
        network_mode: 'host'
    couchdb:
        image: matthiasg/rpi-couchdb:2.0.0
        restart: always
        volumes:
            - ./db:/opt/couchdb/data
        networks:
            - webnet
        ports:
            - '5984:5984'
networks:
    webnet:
