#!/bin/sh
sudo mkdir -p /lumi/files
sudo curl http://update.lumi.education/docker-compose.yml -o /lumi/docker-compose.yml
cd /lumi; sudo docker-compose pull;
cd /lumi; sudo docker-compose down --remove-orhphans;
cd /lumi; sudo docker-compose up -d;
