#!/bin/sh
sudo mkdir -p /lumi/files
sudo curl http://update.lumi.education/docker-compose.yml -o /lumi/docker-compose.yml
sudo docker-compose pull
sudo docker-compose down --remove-orhphans
sudo docker-compose up -d