export interface Action {
	id?: string;
	type: string;
	payload;
}

export const AUTH_GET_SESSION_REQUEST = 'AUTH_GET_SESSION_REQUEST';
export const AUTH_GET_SESSION_SUCCESS = 'AUTH_GET_SESSION_SUCCESS';
export const AUTH_GET_SESSION_ERROR = 'AUTH_GET_SESSION_ERROR';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
export const COLLECTION_CREATEMETA_REQUEST = 'COLLECTION/CREATEMETA/REQUEST';
export const COLLECTION_CREATEMETA_SUCCESS = 'COLLECTION/CREATEMETA/SUCCESS';
export const COLLECTION_CREATEMETA_ERROR = 'COLLECTION/CREATEMETA/ERROR';
export const COLLECTION_GET_REQUEST = 'COLLECTION_GET_REQUEST';
export const COLLECTION_GET_SUCCESS = 'COLLECTION_GET_SUCCESS';
export const COLLECTION_GET_ERROR = 'COLLECTION_GET_ERROR';
export const COLLECTION_UPDATE_SUCCESS = 'COLLECTION_UPDATE_SUCCESS';
export const COLLECTION_UPDATE_USERDATA_SUCCESS = 'COLLECTION_UPDATE_USERDATA_SUCCESS';
export const COLLECTION_SUBMIT_REQUEST = 'COLLECTION/SUBMIT/REQUEST';
export const COLLECTION_SUBMIT_SUCCESS = 'COLLECTION/SUBMIT/SUCCESS';
export const COLLECTION_SUBMIT_ERROR = 'COLLECTION/SUBMIT/ERROR';
export const ACCOUNT_RECOVERY_RESET_OPTIONS_ERROR = 'ACCOUNT_RECOVERY_RESET_OPTIONS_ERROR';
export const ACCOUNT_RECOVERY_RESET_OPTIONS_RECEIVE = 'ACCOUNT_RECOVERY_RESET_OPTIONS_RECEIVE';
