export const AUTH_GET_SESSION_REQUEST = 'AUTH_GET_SESSION_REQUEST';
export const AUTH_GET_SESSION_SUCCESS = 'AUTH_GET_SESSION_SUCCESS';
export const AUTH_GET_SESSION_ERROR = 'AUTH_GET_SESSION_ERROR';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';
export const AUTH_LOGIN_CHECK_USERNAME_REQUEST =
    'AUTH_LOGIN_CHECK_USERNAME_REQUEST';
export const AUTH_LOGIN_CHECK_USERNAME_SUCCESS =
    'AUTH_LOGIN_CHECK_USERNAME_SUCCESS';
export const AUTH_LOGIN_CHECK_USERNAME_ERROR =
    'AUTH_LOGIN_CHECK_USERNAME_ERROR';
export const AUTH_LOGIN_SET_PASSWORD_REQUEST =
    'AUTH_LOGIN_SET_PASSWORD_REQUEST';
export const AUTH_LOGIN_SET_PASSWORD_SUCCESS =
    'AUTH_LOGIN_SET_PASSWORD_SUCCESS';
export const AUTH_LOGIN_SET_PASSWORD_ERROR = 'AUTH_LOGIN_SET_PASSWORD_ERROR';
