export const AUTH_LOGIN_CHECK_USERNAME_REQUEST =
    'AUTH_LOGIN_CHECK_USERNAME_REQUEST';
export const AUTH_LOGIN_CHECK_USERNAME_SUCCESS =
    'AUTH_LOGIN_CHECK_USERNAME_SUCCESS';
export const AUTH_LOGIN_CHECK_USERNAME_ERROR =
    'AUTH_LOGIN_CHECK_USERNAME_ERROR';
export const AUTH_LOGIN_SET_PASSWORD_REQUEST =
    'AUTH_LOGIN_SET_PASSWORD_REQUEST';
export const AUTH_LOGIN_SET_PASSWORD_SUCCESS =
    'AUTH_LOGIN_SET_PASSWORD_SUCCESS';
export const AUTH_LOGIN_SET_PASSWORD_ERROR = 'AUTH_LOGIN_SET_PASSWORD_ERROR';
